vim.cmd("set noexpandtab")
vim.cmd("syntax on")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set smartindent")
vim.cmd("set autoindent")
vim.cmd("set smarttab")
vim.cmd("set wildmenu")
vim.cmd("set nocompatible")
vim.cmd("set mouse=c")
vim.cmd("set mouse=a")
vim.cmd("set splitright")
vim.cmd("set splitbelow")
vim.cmd("set colorcolumn=80")
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.cmd("let g:user42 = 'aroualid'")
vim.cmd("let g:mail42 = 'aroualid@student.42.fr'")
vim.api.nvim_set_keymap("i", "jj", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader><Left>", "<C-W>h", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader><Down>", "<C-W>j", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader><Up>", "<C-W>k", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader><Right>", "<C-W>l", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>v", "<C-W>v", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>s", "<C-W>s", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>th", ":ToggleTerm<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<leader>tv", ":vert term<CR>i", { noremap = true })
vim.api.nvim_set_keymap("t", "<esc>", "<LeftMouse>", { noremap = true })
